//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CIE_2_PROJECT
{
    public partial class MyProposals
    {
        /// <summary>
        /// btnAll control.
        /// </summary>
        protected global::System.Web.UI.WebControls.LinkButton btnAll;

        /// <summary>
        /// btnPending control.
        /// </summary>
        protected global::System.Web.UI.WebControls.LinkButton btnPending;

        /// <summary>
        /// btnAccepted control.
        /// </summary>
        protected global::System.Web.UI.WebControls.LinkButton btnAccepted;

        /// <summary>
        /// btnRejected control.
        /// </summary>
        protected global::System.Web.UI.WebControls.LinkButton btnRejected;

        /// <summary>
        /// rptProposals control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Repeater rptProposals;

        /// <summary>
        /// pnlEmpty control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Panel pnlEmpty;
    }
}
